// Copyright (C) 2023-2024 Timo Früh
// The full copyright notice can be found in ../src/main.cpp

#pragma once

#include <string>
#include <vector>


// This namespace contains all functionality related to the verb database.
namespace verbDB {

    // Declare all verbs.
    extern const std::vector<std::wstring> acheter;
    extern const std::vector<std::wstring> agir;
    extern const std::vector<std::wstring> aimer;
    extern const std::vector<std::wstring> aller;
    extern const std::vector<std::wstring> amener;
    extern const std::vector<std::wstring> apercevoir;
    extern const std::vector<std::wstring> apparaitre;
    extern const std::vector<std::wstring> appeler;
    extern const std::vector<std::wstring> applaudir;
    extern const std::vector<std::wstring> appuyer;
    extern const std::vector<std::wstring> atteindre;
    extern const std::vector<std::wstring> attendre;
    extern const std::vector<std::wstring> avancer;
    extern const std::vector<std::wstring> avoir;
    extern const std::vector<std::wstring> battre;
    extern const std::vector<std::wstring> bavarder;
    extern const std::vector<std::wstring> boire;
    extern const std::vector<std::wstring> chercher;
    extern const std::vector<std::wstring> choisir;
    extern const std::vector<std::wstring> commencer;
    extern const std::vector<std::wstring> conduire;
    extern const std::vector<std::wstring> confondre;
    extern const std::vector<std::wstring> connaitre;
    extern const std::vector<std::wstring> construire;
    extern const std::vector<std::wstring> courir;
    extern const std::vector<std::wstring> couvrir;
    extern const std::vector<std::wstring> craindre;
    extern const std::vector<std::wstring> croire;
    extern const std::vector<std::wstring> cueillir;
    extern const std::vector<std::wstring> decevoir;
    extern const std::vector<std::wstring> demolir;
    extern const std::vector<std::wstring> descendre;
    extern const std::vector<std::wstring> detruire;
    extern const std::vector<std::wstring> devoir;
    extern const std::vector<std::wstring> dire;
    extern const std::vector<std::wstring> disparaitre;
    extern const std::vector<std::wstring> donner;
    extern const std::vector<std::wstring> dormir;
    extern const std::vector<std::wstring> ecrire;
    extern const std::vector<std::wstring> effacer;
    extern const std::vector<std::wstring> employer;
    extern const std::vector<std::wstring> enlever;
    extern const std::vector<std::wstring> entendre;
    extern const std::vector<std::wstring> entrer;
    extern const std::vector<std::wstring> envoyer;
    extern const std::vector<std::wstring> esperer;
    extern const std::vector<std::wstring> essayer;
    extern const std::vector<std::wstring> essuyer;
    extern const std::vector<std::wstring> eteindre;
    extern const std::vector<std::wstring> etre;
    extern const std::vector<std::wstring> exagerer;
    extern const std::vector<std::wstring> faire;
    extern const std::vector<std::wstring> falloir;
    extern const std::vector<std::wstring> fermer;
    extern const std::vector<std::wstring> finir;
    extern const std::vector<std::wstring> fuir;
    extern const std::vector<std::wstring> grimper;
    extern const std::vector<std::wstring> guerir;
    extern const std::vector<std::wstring> habiter;
    extern const std::vector<std::wstring> inventer;
    extern const std::vector<std::wstring> jeter;
    extern const std::vector<std::wstring> joindre;
    extern const std::vector<std::wstring> lancer;
    extern const std::vector<std::wstring> laver;
    extern const std::vector<std::wstring> lire;
    extern const std::vector<std::wstring> maigrir;
    extern const std::vector<std::wstring> manger;
    extern const std::vector<std::wstring> mener;
    extern const std::vector<std::wstring> mentir;
    extern const std::vector<std::wstring> mettre;
    extern const std::vector<std::wstring> monter;
    extern const std::vector<std::wstring> mourir;
    extern const std::vector<std::wstring> nager;
    extern const std::vector<std::wstring> naitre;
    extern const std::vector<std::wstring> nettoyer;
    extern const std::vector<std::wstring> obeir;
    extern const std::vector<std::wstring> offrir;
    extern const std::vector<std::wstring> ouvrir;
    extern const std::vector<std::wstring> paraitre;
    extern const std::vector<std::wstring> parler;
    extern const std::vector<std::wstring> partir;
    extern const std::vector<std::wstring> payer;
    extern const std::vector<std::wstring> peindre;
    extern const std::vector<std::wstring> perdre;
    extern const std::vector<std::wstring> peser;
    extern const std::vector<std::wstring> plaire;
    extern const std::vector<std::wstring> pleuvoir;
    extern const std::vector<std::wstring> pouvoir;
    extern const std::vector<std::wstring> prendre;
    extern const std::vector<std::wstring> produire;
    extern const std::vector<std::wstring> proteger;
    extern const std::vector<std::wstring> reagir;
    extern const std::vector<std::wstring> recevoir;
    extern const std::vector<std::wstring> reduire;
    extern const std::vector<std::wstring> reflechir;
    extern const std::vector<std::wstring> remplir;
    extern const std::vector<std::wstring> rendre;
    extern const std::vector<std::wstring> repondre;
    extern const std::vector<std::wstring> reussir;
    extern const std::vector<std::wstring> rire;
    extern const std::vector<std::wstring> rompre;
    extern const std::vector<std::wstring> sAsseoir;
    extern const std::vector<std::wstring> savoir;
    extern const std::vector<std::wstring> secher;
    extern const std::vector<std::wstring> sEnnuyer;
    extern const std::vector<std::wstring> sentir;
    extern const std::vector<std::wstring> sePlaindre;
    extern const std::vector<std::wstring> sePromener;
    extern const std::vector<std::wstring> seRejouir;
    extern const std::vector<std::wstring> servir;
    extern const std::vector<std::wstring> seTaire;
    extern const std::vector<std::wstring> sInquieter;
    extern const std::vector<std::wstring> sortir;
    extern const std::vector<std::wstring> souffrir;
    extern const std::vector<std::wstring> suffire;
    extern const std::vector<std::wstring> suivre;
    extern const std::vector<std::wstring> tenir;
    extern const std::vector<std::wstring> traduire;
    extern const std::vector<std::wstring> valoir;
    extern const std::vector<std::wstring> vendre;
    extern const std::vector<std::wstring> venir;
    extern const std::vector<std::wstring> vieillir;
    extern const std::vector<std::wstring> vivre;
    extern const std::vector<std::wstring> voir;
    extern const std::vector<std::wstring> vouloir;
}
